name: Build
# 
on: 
    push:
        branches: ["main"]
    schedule:
      - cron: "0 */8 * * *" # Every 8 hours

env:
  ANSIBLE_VERSION: 10.6.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noNewCommitBehavior: current
          noVersionBumpBehavior: current

      - name: "Created tag"
        run: echo "tag ${{ steps.semver.outputs.next }}"

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{github.actor}}
      #     password: ${{secrets.GITHUB_TOKEN}}

      # - name: Build image
      #   run: docker build --build-arg PROVIDERS=./plugins -t ghcr.io/ciaranmcandrew/ansible-agent3:latest -t ghcr.io/ciaranmcandrew/ansible-agent3:${{ steps.semver.outputs.next }} .

      # - name: Publish image
      #   run: docker push --all-tags ghcr.io/ciaranmcandrew/ansible-agent3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build --build-arg PROVIDERS=./plugins --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION -t ${{ secrets.DOCKERHUB_USERNAME }}/ansible-agent:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/ansible-agent:$ANSIBLE_VERSION .

      - name: Publish image
        run: docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/ansible-agent

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.semver.outputs.next }}
          release_name: Release ${{ steps.semver.outputs.next }}
          body: ""
          draft: false
          prerelease: false
